### ISSUE TITLE
Accessing fields of a defined type which is as pointer to struct

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#151]
The following correct go code crashes Gobra
```go
type G *struct {
	i int
}

func changeI(g G, i int) {
	g.i = i
}
```
with the following stack trace
```
[error] Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
[error] 	at scala.Predef$.require(Predef.scala:325)
[error] 	at viper.gobra.ast.internal.Deref$.apply(Program.scala:602)
[error] 	at viper.gobra.frontend.Desugar$Desugarer.$anonfun$applyMemberPathD$1(Desugar.scala:1139)
[error] 	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
[error] 	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
[error] 	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
[error] 	at viper.gobra.frontend.Desugar$Desugarer.applyMemberPathD(Desugar.scala:1137)
[error] 	at viper.gobra.frontend.Desugar$Desugarer.$anonfun$fieldSelectionD$1(Desugar.scala:821)
[error] 	at viper.gobra.util.DesugarWriter$Writer.map(DesugarWriter.scala:36)
[error] 	at viper.gobra.frontend.Desugar$Desugarer.fieldSelectionD(Desugar.scala:820)
```

**Comment by jcp19** [comment]
this seems to fail due to a runtime check in the `apply` method of `Deref`:
```scala
    require(exp.typ.isInstanceOf[PointerT])
```
which may not be strictly required
