### ISSUE TITLE
Gobra crashes with programs that rely on the built-in stubs

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#184]
When a program such as [this](https://github.com/viperproject/gobra/blob/add-sync-stubs/src/test/resources/regressions/features/defunc/mutex1.gobra) is verified in Gobra, it crashes with
```
[error] Exception in thread "main" java.lang.IllegalStateException: managed file system can no longer be retained when it is already closed
[error] 	at viper.gobra.frontend.PackageResolver$ManagedFileSystem.retain(PackageResolver.scala:286)
[error] 	at viper.gobra.frontend.PackageResolver$JarFileResource.<init>(PackageResolver.scala:269)
[error] 	at viper.gobra.frontend.PackageResolver$JarResource.resolve(PackageResolver.scala:235)
[error] 	at viper.gobra.frontend.PackageResolver$JarResource.resolve$(PackageResolver.scala:234)
[error] 	at viper.gobra.frontend.PackageResolver$BaseJarResource.resolve(PackageResolver.scala:253)
[error] 	at viper.gobra.frontend.PackageResolver$BaseJarResource.resolve(PackageResolver.scala:253)
[error] 	at viper.gobra.frontend.PackageResolver$.$anonfun$getLookupPath$1(PackageResolver.scala:112)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:375)
[error] 	at viper.gobra.frontend.PackageResolver$.getLookupPath(PackageResolver.scala:112)
[error] 	at viper.gobra.frontend.PackageResolver$.resolve(PackageResolver.scala:40)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.parseAndTypeCheck$1(MemberResolution.scala:178)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.$anonfun$tryPackageLookup$12(MemberResolution.scala:214)
[error] 	at scala.Option.getOrElse(Option.scala:201)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.getTypeChecker$1(MemberResolution.scala:214)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryPackageLookup(MemberResolution.scala:218)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryPackageLookup$(MemberResolution.scala:175)
```

The bug does **NOT** seem to be triggered in our testing framework (locally or CI) or when I run Gobra inside an IDE (IntelliJ). I only run into it when I execute Gobra from *sbt*

In order to trigger this particular instance of the bug, you must be in branch `add-sync-stubs` or at some point of the git history where the changes from the corresponding PR (#179) have been merged.

**Comment by jcp19** [comment]
One quick and dirty way to fix it would be to disable reference counting in the class `ManagedFileSystem` of the file `src/main/scala/viper/gobra/frontend/PackageResolver.scala`. I will look into this and try to fix it in a more elegant way
