### ISSUE TITLE
ManagedFileSystem crashes when importing stubs

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#219]
The following excerpt causes Gobra to crash with a **java.nio.file.FileSystemAlreadyExistsException** (stack trace shown at the end of the issue):
```go
package path

import "time"

func ExpTimeToDuration(expTime uint8) time.Duration {
	return (time.Duration(expTime) + 1) * time.Duration(expTimeUnit) * time.Second
}
```
I'm assuming at the moment that you are running on Gobra on the `add-more-stubs` branch or in any other branch that incorporated its changes (and, in particular, that contains the stubs for the time package).

Once again, this issue only occurs when Gobra is run on sbt in the terminal. Running it from an IDE will sidestep the issue.

Stack trace:
```
[error] Exception in thread "main" java.nio.file.FileSystemAlreadyExistsException
[error] 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
[error] 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
[error] 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
[error] 	at viper.gobra.frontend.PackageResolver$ManagedFileSystem.<init>(PackageResolver.scala:311)
[error] 	at viper.gobra.frontend.PackageResolver$BaseJarResource.filesystem$lzycompute(PackageResolver.scala:285)
[error] 	at viper.gobra.frontend.PackageResolver$BaseJarResource.filesystem(PackageResolver.scala:285)
[error] 	at viper.gobra.frontend.PackageResolver$BaseJarResource.<init>(PackageResolver.scala:286)
[error] 	at viper.gobra.frontend.PackageResolver$.$anonfun$getResource$2(PackageResolver.scala:112)
[error] 	at scala.Option.flatMap(Option.scala:283)
[error] 	at viper.gobra.frontend.PackageResolver$.getResource(PackageResolver.scala:104)
[error] 	at viper.gobra.frontend.PackageResolver$.getBuiltInResource(PackageResolver.scala:89)
[error] 	at viper.gobra.frontend.PackageResolver$.getLookupPath(PackageResolver.scala:135)
[error] 	at viper.gobra.frontend.PackageResolver$.resolve(PackageResolver.scala:50)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.parseAndTypeCheck$1(MemberResolution.scala:221)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.$anonfun$tryPackageLookup$12(MemberResolution.scala:257)
[error] 	at scala.Option.getOrElse(Option.scala:201)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.getTypeChecker$1(MemberResolution.scala:257)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryPackageLookup(MemberResolution.scala:261)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryPackageLookup$(MemberResolution.scala:219)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.tryPackageLookup(TypeInfoImpl.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryUnqualifiedBuiltInPackageLookup(MemberResolution.scala:300)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.tryUnqualifiedBuiltInPackageLookup$(MemberResolution.scala:299)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.tryUnqualifiedBuiltInPackageLookup(TypeInfoImpl.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.resolution.MemberResolution.$anonfun$tryUnqualifiedPackageLookup$1(MemberResolution.scala:296)
[error] 	at org.bitbucket.inkytonik.kiama.attribution.AttributionCore$CachedAttribute.liftedTree1$1(AttributionCore.scala:58)
```

**Comment by jcp19** [comment]
This error also occurs on the `continue-string-parsing` branch and I assume that it would also be triggered in the master branch. I've seen it occur inside the Gobra IDE with the following code

```go
package addr

type IA struct {
	I ISD
	A AS
}

type ISD uint16
type AS uint64
func IAFromString(s string) (IA, error)

requires ia != nil ==> acc(ia)
ensures ia != nil ==> acc(ia)
func (ia *IA) Set(s string) error {
	pIA, err := IAFromString(s)
	if err != nil {
		return err
	}
	*ia = pIA
	return nil
}
```

**Comment by ArquintL** [comment]
The same error occurs with the second code snippet? Now I'm really confused as the second code does not even contain an import

**Comment by ArquintL** [comment]
Potential ideas for investigating this further:
- could you please debug whether a file system is created multiple times for the `builtin` subfolder in `resources`
- can you check whether these file systems are correctly closed? Maybe Gobra jumps over the stmt `_ = pkgFiles.map(_.close())` in MemberResolution.tryPackageLookup
