### ISSUE TITLE
Kiama cycle when defining struct field X of type []X

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#235]
The following code leads to a cycle in Kiama
```go
type Location struct {
	name string
	zone []zone // Leads to cycle in kiama
	
}

type zone struct {
	name   string
	offset int
	isDST  bool
}

```

Error
```
[error] Exception in thread "main" java.lang.IllegalStateException: Cycle detected in attribute evaluation 'store' at zone
[error] 	at org.bitbucket.inkytonik.kiama.attribution.Attribute.reportCycle(Attribute.scala:24)
[error] 	at org.bitbucket.inkytonik.kiama.attribution.AttributionCore$CachedAttribute.apply(AttributionCore.scala:54)
[error] 	at viper.gobra.util.Memoization.apply(Computation.scala:23)
[error] 	at viper.gobra.util.Memoization.apply$(Computation.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.apply(BaseTyping.scala:71)
[error] 	at viper.gobra.util.Validity.valid(Computation.scala:38)
[error] 	at viper.gobra.util.Validity.valid$(Computation.scala:38)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.valid(BaseTyping.scala:71)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.selfWellDefined(BaseTyping.scala:56)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.selfWellDefined$(BaseTyping.scala:54)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.selfWellDefined(TypeInfoImpl.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.$anonfun$childrenWellDefined$1(BaseTyping.scala:52)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.$anonfun$childrenWellDefined$1$adapted(BaseTyping.scala:52)
[error] 	at scala.collection.IterableOnceOps.forall(IterableOnce.scala:577)
[error] 	at scala.collection.IterableOnceOps.forall$(IterableOnce.scala:574)
[error] 	at scala.collection.AbstractIterable.forall(Iterable.scala:919)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.childrenWellDefined(BaseTyping.scala:52)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping.childrenWellDefined$(BaseTyping.scala:52)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.childrenWellDefined(TypeInfoImpl.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.safe(BaseTyping.scala:73)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.safe(BaseTyping.scala:71)
[error] 	at viper.gobra.util.Safety.apply(Computation.scala:31)
[error] 	at viper.gobra.util.Safety.apply$(Computation.scala:31)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.viper$gobra$util$Memoization$$super$apply(BaseTyping.scala:71)
[error] 	at viper.gobra.util.Memoization.$anonfun$store$1(Computation.scala:21)
[error] 	at org.bitbucket.inkytonik.kiama.attribution.AttributionCore$CachedAttribute.liftedTree1$1(AttributionCore.scala:58)
[error] 	at org.bitbucket.inkytonik.kiama.attribution.AttributionCore$CachedAttribute.apply(AttributionCore.scala:56)
[error] 	at viper.gobra.util.Memoization.apply(Computation.scala:23)
[error] 	at viper.gobra.util.Memoization.apply$(Computation.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.apply(BaseTyping.scala:71)
[error] 	at viper.gobra.util.Validity.valid(Computation.scala:38)
[error] 	at viper.gobra.util.Validity.valid$(Computation.scala:38)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$1.valid(BaseTyping.scala:71)
[error] 	at viper.gobra.frontend.info.implementation.typing.IdTyping.wellDefActualRegular(IdTyping.scala:102)
[error] 	at viper.gobra.frontend.info.implementation.typing.IdTyping.wellDefActualRegular$(IdTyping.scala:48)
[error] 	at viper.gobra.frontend.info.implementation.TypeInfoImpl.wellDefActualRegular(TypeInfoImpl.scala:23)
[error] 	at viper.gobra.frontend.info.implementation.typing.IdTyping.$anonfun$wellDefID$1(IdTyping.scala:28)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$2.compute(BaseTyping.scala:87)
[error] 	at viper.gobra.frontend.info.implementation.typing.BaseTyping$$anon$2.compute(BaseTyping.scala:81)
[error] 	at viper.gobra.util.Computation.apply(Computation.scala:16)
```

**Comment by jcp19** [comment]
this is also the case when we define a defining struct field `X` of type `X`, e.g. 
```go
// SCION is the header of a SCION packet.
type SCION struct {
	Version uint8
	PayloadLen uint16
	// PathType PathType //(joao) leads to cycle in kiama
	// Path Path //(joao) leads to cycles in kiama
}
```
