### ISSUE TITLE
Buggy encoding of slices of interfaces

### ISSUE THREAD

**Issue by jcp19** [viperproject/gobra#236]
Currently, the encoding of slices of interface{} leads to type errors in the generated viper file
```go
func g(a []interface{}){}

func test5() {
    s := [](interface{}){1, true, []int{1,2,3}}
    g(s)
}
```

Stack trace:
```
[error] Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.AssertionError: assertion failed: Expected both operands to be of sort Seq(S1,S2,...), but found [1] (Seq[Int]) and [True] (Seq[Bool])
[error] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[error] 	at viper.silicon.Silicon.verify(Silicon.scala:199)
[error] 	at viper.silicon.Silicon.verify(Silicon.scala:157)
[error] 	at viper.gobra.backend.Silicon.$anonfun$verify$1(Silicon.scala:27)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
[error] 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: assertion failed: Expected both operands to be of sort Seq(S1,S2,...), but found [1] (Seq[Int]) and [True] (Seq[Bool])
```
The resulting viper file for the excerpt shown in this issue can be found in [workingFile.txt](https://github.com/viperproject/gobra/files/6135164/workingFile.txt).

**Comment by Felalolf** [comment]
The problem is in the desugarer. The literal construction does not apply the implicitConversion function on the arguments and thus the arguments are not typed correctly.
