### ISSUE TITLE
Gobra does not support embedded interfaces

### ISSUE THREAD

**Issue by Dspil** [viperproject/gobra#461]
Example:

file test.go:

package test

```
type Foo interface {
	pred Mem()
	
	FooA() int
}
```

file test2.go:

```
package test2

type Bar interface {
	pred Mem()

	BarA() int
	test.Foo
}

```
Trying to verify file test2.go produces an error.

The problem does not occur only for imported types. Putting the above in a single file like this:

```
package test

type Foo interface {
	pred Mem()
	
	FooA() int
}

type Bar interface {

	BarA() int
	Foo
}
```

produces the following exception:

12:16:58.741 [main] ERROR viper.gobra.GobraRunner$ - An unknown Exception was thrown.
12:16:58.742 [main] ERROR viper.gobra.GobraRunner$ - None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at viper.gobra.frontend.Desugar$NameManager.trimmedSrcText$1(Desugar.scala:3310)
	at viper.gobra.frontend.Desugar$NameManager.$anonfun$srcTextName$3(Desugar.scala:3316)
	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
	at scala.collection.immutable.Vector1.map(Vector.scala:375)
	at viper.gobra.frontend.Desugar$NameManager.$anonfun$srcTextName$2(Desugar.scala:3316)
	at scala.collection.immutable.ArraySeq.$anonfun$map$1(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq.$anonfun$map$1$adapted(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:286)
	at scala.collection.immutable.ArraySeq$.tabulate(ArraySeq.scala:265)
	at scala.collection.ClassTagIterableFactory$AnyIterableDelegate.tabulate(Factory.scala:679)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:71)
	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
	at viper.gobra.frontend.Desugar$NameManager.srcTextName(Desugar.scala:3316)
	at viper.gobra.frontend.Desugar$NameManager.interface(Desugar.scala:3287)
	at viper.gobra.frontend.Desugar$Desugarer.typeD(Desugar.scala:2386)
	at viper.gobra.frontend.Desugar$Desugarer.registerDefinedType(Desugar.scala:2132)
	at viper.gobra.frontend.Desugar$Desugarer.typeD(Desugar.scala:2353)
	at viper.gobra.frontend.Desugar$Desugarer.desugarAllTypeDefVariants(Desugar.scala:427)
	at viper.gobra.frontend.Desugar$Desugarer.$anonfun$packageD$2(Desugar.scala:354)
	at viper.gobra.frontend.Desugar$Desugarer.$anonfun$packageD$2$adapted(Desugar.scala:353)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at viper.gobra.frontend.Desugar$Desugarer.packageD(Desugar.scala:353)
	at viper.gobra.frontend.Desugar$.desugar(Desugar.scala:40)
	at viper.gobra.Gobra.performDesugaring(Gobra.scala:255)
	at viper.gobra.Gobra.$anonfun$verify$5(Gobra.scala:154)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$4(Gobra.scala:153)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$3(Gobra.scala:152)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$1(Gobra.scala:150)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Felalolf** [comment]
Just a small remark, I think the included interfaces are written first in the body of the interface type literal.

**Comment by Dspil** [comment]
> Just a small remark, I think the included interfaces are written first in the body of the interface type literal.

In the scion repository they tend to write them last.

**Comment by jcp19** [comment]
@Dspil can we close this issue?
