### ISSUE TITLE
Closures bug with a declared function type

### ISSUE THREAD

**Issue by Dspil** [viperproject/gobra#503]
The following file produces a gobra error:

```
package pkg

type f func () int

type A interface {
	g() f
}
```

The error is the following:
```
15:24:06.959 [main] ERROR viper.gobra.GobraRunner$ - Logic error: Node P0_PO0 (class viper.gobra.ast.internal.Parameter$Out) :: f_bda1d7d_T. did not match with any implemented case of variable. 
viper.gobra.util.Violation$LogicException: Logic error: Node P0_PO0 (class viper.gobra.ast.internal.Parameter$Out) :: f_bda1d7d_T. did not match with any implemented case of variable. 
	at viper.gobra.util.Violation$.violation(Violation.scala:27)
	at viper.gobra.translator.encodings.combinators.FinalTypeEncoding$$anonfun$expectedMatch$1.applyOrElse(FinalTypeEncoding.scala:23)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner$$anon$1.$anonfun$applyOrElse$1(PartialFunctionCombiner.scala:32)
	at scala.Option.getOrElse(Option.scala:201)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner$$anon$1.applyOrElse(PartialFunctionCombiner.scala:32)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner$$anon$1.$anonfun$applyOrElse$1(PartialFunctionCombiner.scala:32)
	at scala.Option.getOrElse(Option.scala:201)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner$$anon$1.applyOrElse(PartialFunctionCombiner.scala:32)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241)
	at viper.gobra.translator.context.Context.variable(Context.scala:62)
	at viper.gobra.translator.context.Context.variable$(Context.scala:62)
	at viper.gobra.translator.context.ContextImpl.variable(ContextImpl.scala:25)
	at viper.gobra.translator.encodings.defaults.DefaultMethodEncoding.$anonfun$methodDefault$3(DefaultMethodEncoding.scala:36)
	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
	at scala.collection.immutable.Vector1.map(Vector.scala:375)
	at viper.gobra.translator.encodings.defaults.DefaultMethodEncoding.methodDefault(DefaultMethodEncoding.scala:36)
	at viper.gobra.translator.context.DfltTranslatorConfig$$anon$1.method(DfltTranslatorConfig.scala:78)
	at viper.gobra.translator.encodings.interfaces.InterfaceEncoding$$anonfun$method$1.applyOrElse(InterfaceEncoding.scala:99)
	at viper.gobra.translator.encodings.interfaces.InterfaceEncoding$$anonfun$method$1.applyOrElse(InterfaceEncoding.scala:94)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
	at scala.PartialFunction.unapply(PartialFunction.scala:71)
	at scala.PartialFunction.unapply$(PartialFunction.scala:71)
	at scala.runtime.AbstractPartialFunction.unapply(AbstractPartialFunction.scala:27)
	at viper.gobra.translator.encodings.combinators.TypeEncoding$$anonfun$finalMethod$1.applyOrElse(TypeEncoding.scala:324)
	at viper.gobra.translator.encodings.combinators.TypeEncoding$$anonfun$finalMethod$1.applyOrElse(TypeEncoding.scala:324)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
	at scala.PartialFunction.unapply(PartialFunction.scala:71)
	at scala.PartialFunction.unapply$(PartialFunction.scala:71)
	at scala.runtime.AbstractPartialFunction.unapply(AbstractPartialFunction.scala:27)
	at viper.gobra.translator.encodings.combinators.TypeEncoding$$anonfun$member$1.applyOrElse(TypeEncoding.scala:69)
	at viper.gobra.translator.encodings.combinators.TypeEncoding$$anonfun$member$1.applyOrElse(TypeEncoding.scala:68)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:245)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner.$anonfun$safeApply$1(PartialFunctionCombiner.scala:22)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner.safeApply(PartialFunctionCombiner.scala:22)
	at viper.gobra.translator.util.PartialFunctionCombiner$SafeCombiner$$anon$1.applyOrElse(PartialFunctionCombiner.scala:32)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241)
	at viper.gobra.translator.context.Context.member(Context.scala:66)
	at viper.gobra.translator.context.Context.member$(Context.scala:66)
	at viper.gobra.translator.context.ContextImpl.member(ContextImpl.scala:25)
	at viper.gobra.translator.encodings.programs.ProgramsImpl.goM$1(ProgramsImpl.scala:29)
	at viper.gobra.translator.encodings.programs.ProgramsImpl.$anonfun$translate$2(ProgramsImpl.scala:33)
	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
	at scala.collection.immutable.Vector1.map(Vector.scala:375)
	at viper.gobra.translator.encodings.programs.ProgramsImpl.translate(ProgramsImpl.scala:33)
	at viper.gobra.translator.Translator$.translate(Translator.scala:24)
	at viper.gobra.Gobra.performViperEncoding(Gobra.scala:282)
	at viper.gobra.Gobra.$anonfun$verify$7(Gobra.scala:159)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$6(Gobra.scala:158)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$5(Gobra.scala:157)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$4(Gobra.scala:156)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$3(Gobra.scala:155)
	at scala.util.Either.flatMap(Either.scala:352)
	at viper.gobra.Gobra.$anonfun$verify$1(Gobra.scala:153)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by budney** [comment]
Hit the same crash via a different trigger — not through an interface method return type, but a
plain function *parameter* declared with a named function type, with no interface involved at
all:

```go
package pkg

type Interceptor func(x int) int

func handler(interceptor Interceptor) int {
	return 1
}
```

```
Logic error: Node interceptor_V0 (class viper.gobra.ast.internal.Parameter$In) ::
Interceptor_...T did not match with any implemented case of variable.
```

Same `DefaultMethodEncoding` → `Context.variable` crash signature as the original report, and it
reproduces even with `//@ trusted` on `handler` and even when `interceptor` is never called in the
body — so encoding the method's *signature* alone is enough to trigger it, independent of the
original report's interface-return-type path. Swapping the parameter to the equivalent anonymous
function type (`func(x int) int` instead of `Interceptor`) avoids the crash entirely, same
workaround shape as here.

Ran into this annotating `protoc-gen-go-grpc`-generated code, where a real gRPC handler
signature takes a named interceptor func type (`grpc.UnaryServerInterceptor`) as a parameter —
so this is a second, parameter-position manifestation of what looks like the same root cause
(any named function type reaching `DefaultMethodEncoding`'s Viper method encoding).
